# После запуска через docker-compose up можно открыть в браузере localhost:8081, localhost:8080 
# и подключиться к Postgresql через localhost:5432

version: '3'
services:
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: db
        ports:
            - 5432:5432
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080